name: concur-replica-spa
version: 0.1.0.0
github: "githubuser/concur-replica-spa"
license: BSD3
author: "Gaute Berge"
maintainer: "gaute.berge@gmail.com"
copyright: "2022 Gaute Berge"
language: GHC2021

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/concur-replica-spa#readme>

dependencies:
  - base >= 4.7 && < 5
  - concur-core
  - replica
  - concur-replica
  - relude
  - wai
  - stm
  - mtl
  - wai-middleware-static
  - websockets
  - wreq
  - aeson
  - time

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - OverloadedRecordDot
  # - OverloadedRecordUpdate

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  concur-replica-spa-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - concur-replica-spa
    when:
      - condition: false
        other-modules: Paths_concur_replica_spa

tests:
  concur-replica-spa-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - concur-replica-spa
